server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # THIS IS THE MAGIC LINE!
        # It tells Nginx to redirect all 404s back to index.html
        try_files $uri $uri/ /index.html; 
    }
}
