apiVersion: v1
kind: Secret
metadata:
  name: upskill-secrets
  namespace: upskill-namespace
type: Opaque
stringData: 
  # Backend Sensitive Data
  JWT_SECRET: "thala-aditya"
  MONGODB_URL: "mongodb+srv://aditya1332002_db_user:IsZmCdq1AKEyRrAp@cluster0.v1kepay.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  MAIL_USER: "adk14639@gmail.com"
  MAIL_PASS: "mgdqvodlslpyfgpw"
  RAZORPAY_SECRET: "jPb0pBJ5oMrOqsHe3aKOYSCH"
  API_KEY: "527651512237986"
  API_SECRET: "9MveTuIgFo9CGPzzxkWlDqxPLE0"
  GOOGLE_CLIENT_SECRET: "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"
