apiVersion: v1
kind: Service
metadata:
  name: upskill-backend-service
  namespace: upskill-namespace
spec:
  type: NodePort
  selector:
    app: upskill-backend # This connects the Service to your 3 Deployment Pods!
  ports:
    - protocol: TCP
      port: 4000         # The port this Service listens on internally
      targetPort: 4000   # The port your Node.js container is running on
      nodePort: 31000    # The port exposed to your physical Linux machine
