apiVersion: v1
kind: Service
metadata:
  name: upskill-frontend-service
  namespace: upskill-namespace
spec:
  type: NodePort
  selector:
    app: upskill-frontend # Connects directly to the frontend Pods
  ports:
    - protocol: TCP
      port: 80          # Internal cluster port
      targetPort: 80    # Port the React container is listening on
      nodePort: 30000     # The port mapped to your physical machine browser
